# Next Steps

As seen in the results, we did time series analysis on the outage data. We used a year's worth of data when creating our functions and graphs, which was useful in creating visuals that show us trends throughout 2025. However, a year's worth of data is not enough to create a model that could help us predict outage trends in coming years because the model may be shortsighted. If we could attain multiple years of outage data we could create a model that utilities can use for forecasting. Though outage data is subject to change year-to-year due to yearly differences in weather, the model can still give us insight into general outage trends throughout the year. This way utilities can gather their resources in preparation for time periods with large outages.

In addition to forecasting, we can also use this package to make a more interactive experience. R offers a package called Shiny that can be used to create interactive web applications, making our functionality more accessible to users that want learn more about their outage data. Users would be able to access the app directly and upload their outage data, and we can configure the app to show visuals and metrics of their choosing. Here are some additional ideas that could be helpful for our target audience:
- Incorporate user-inputted fields (e.g. target KPI) so that users could compare their graphs/metrics against their target. 
- Add interactive filters such as check boxes, radio buttons, and drop downs to narrow the data in the report based on user need (e.g. viewing just Manhattan data instead of all 6 boroughs)
