---
title: "borough_analysis"
authors: Jiwon Bae (jb5234) and Hillary Rodriguez (hnr2112)
execute:
  echo: true
  warning: false
  message: false
format:
  html:
    fig-width: 6
    fig-height: 4
    out-width: 60%
    embed-resources: true
---

## 

```{r}

df <-read.csv("../data/PackageData.csv", stringsAsFactors = TRUE)

```

```{r}
library(dplyr)

outages <- filter(df, OUTAGEFLAG == 1)
outages <- outages |>
  mutate(
    start_ts = lubridate::ymd_hms(STARTDATE, tz = "UTC"),
    rest_ts  = lubridate::ymd_hms(RESTDATE,  tz = "UTC"),
    
    # Use start time as the "event day" for aggregation
    outage_day = as.Date(start_ts),
    duration_mins = as.numeric(difftime(rest_ts, start_ts, units = "mins"))
  )

quartiles <- outages %>%
  group_by(XBORO) %>%
  summarise(
    Q1 = quantile(duration_mins, 0.25),
    Median = median(duration_mins),
    Q3 = quantile(duration_mins, 0.75),
    .groups = "drop"
  ) %>%
  tidyr::pivot_longer(cols = c(Q1, Median, Q3),
                      names_to = "stat",
                      values_to = "y")

```

```{r}

library(ggplot2)

ggplot(df, aes(x=XBORO))+
  geom_bar(fill="#FFD580", color="orange")+
  labs(x="Borough", y="Count of Event", title ="Event Count from Oct 2024 to Oct 2025 by Borough")


```

```{r}
ggplot(outages, aes(x=XBORO))+
  geom_bar(fill="cornflowerblue", color="blue")+
  labs(x="Borough", y="Count of Outages", title ="Outage Count from Oct 2024 to Oct 2025 by Borough")
```

```{r}
ggplot(outages, aes(x = XBORO, y = duration_mins)) +
  geom_boxplot(outliers = FALSE) +
  labs(title="Outage Duration by Borough",
       x= "Borough",
       y="Duration in Minutes") +
  geom_text(
    data = quartiles,
    aes(x = XBORO, y = y, label = round(y, 2)),
    vjust = -0.5,  # Adjust vertical position
    color = "black",
    size = 2
  ) +
  theme(
    axis.text.x = element_text(size = 8)
  )
```

```{r}
library(ggridges)

remove_outliers <- function(x, na.rm = TRUE, coef = 1.5) {
  qnt <- quantile(x, probs = c(0.25, 0.75), na.rm = na.rm)
  iqr <- qnt[2] - qnt[1]
  x >= (qnt[1] - coef * iqr) & x <= (qnt[2] + coef * iqr)
}

outages_clean <- outages %>%
  group_by(XBORO) %>%
  filter(remove_outliers(TOTALCUSTAFFECTED)) %>%
  ungroup()

ggplot(outages_clean, aes(x = TOTALCUSTAFFECTED, y = XBORO)) +
geom_density_ridges(scale = 1.2, rel_min_height = 0.01, fill = "lightblue", alpha = 0.5) +
theme_ridges() +
theme(legend.position = "none") +
labs(title = "Ridgeline Plots of Total Cust Affected by Borough",
     x = "Total Customers Affected", 
     y = "Borough")
```
