---
title: "Data Cleaning"
authors: Jiwon Bae (jb5234) and Hillary Rodriguez (hnr2112)
execute:
  echo: true
  warning: false
  message: false
format:
  html:
    fig-width: 6
    fig-height: 4
    out-width: 60%
    embed-resources: true
---

```{r}
library(readxl)
library(tidyverse)
library(lubridate)

# Raw data not provided
raw_data_path <- fs::path("..", "data", "EDAV_ConEd_Data.xlsx")
df <- readxl::read_excel(raw_data_path)
```

```{r}
df_tidy <- df |>
  
  # Clean up date columns BEFORE parsing
  mutate(
    STARTDATE = na_if(str_trim(STARTDATE), ""),
    RESTDATE  = na_if(str_trim(RESTDATE), ""),
    COMPDATE  = na_if(str_trim(COMPDATE), "")
  ) |>
  
  # Parse using flexible parser
  mutate(
    STARTDATE = parse_date_time(STARTDATE, orders = c("Ymd HMS", "Ymd HM", "Ymd")),
    RESTDATE  = parse_date_time(RESTDATE,  orders = c("Ymd HMS", "Ymd HM", "Ymd")),
    COMPDATE  = parse_date_time(COMPDATE,  orders = c("Ymd HMS", "Ymd HM", "Ymd"))
  ) |>
  
  # Make XBORO uppercase
  mutate(XBORO = toupper(XBORO)) |>
  
  # Drop rows with missing critical values
  filter(
    !is.na(COMPDATE),
    !is.na(TOTALCUSTAFFECTED)
  ) |>
  
  # Drop ERT column
  select(-ERT)

summary(df_tidy)
```

```{r}
# Start Date < Restoration Date <= Complete Date condition check
df_tidy |>
  filter(!(STARTDATE <= RESTDATE & RESTDATE <= COMPDATE)) |>
  select(STARTDATE, RESTDATE, COMPDATE, everything()) |>
  print(n = 50)

```

```{r}
# Fix year
df_fix_year <- df_tidy |>
  mutate(
    RESTDATE = if_else(
      year(RESTDATE) == 2023,
      RESTDATE %m+% years(1),  # add one year
      RESTDATE
    ),
    COMPDATE = if_else(
      year(COMPDATE) == 2023,
      COMPDATE %m+% years(1),  # add one year
      COMPDATE
    )
  )

df_fix_year |>
  filter(!(STARTDATE <= RESTDATE & RESTDATE <= COMPDATE)) |>
  select(STARTDATE, RESTDATE, COMPDATE, everything()) |>
  print(n = 50)
```

```{r}
# Finalize cleaning
df_clean <- df_fix_year |>
  filter((STARTDATE <= RESTDATE & RESTDATE <= COMPDATE)) |>
  select(STARTDATE, RESTDATE, COMPDATE, everything())

# Save
output_data_path <- fs::path("..", "data", "PackageData.csv")
# write_csv(df_clean, output_data_path)
```
